export const CHOOSE_DATA_PLAN = "CHOOSE_DATA_PLAN";

export const GET_DATA_PLANS = "GET_DATA_PLANS";
export const GET_DATA_PLANS_PENDING = "GET_DATA_PLANS_PENDING";
export const GET_DATA_PLANS_FULFILLED = "GET_DATA_PLANS_FULFILLED";
export const GET_DATA_PLANS_REJECTED = "GET_DATA_PLANS_REJECTED";

export const INITIALIZE = "INITIALIZE";
export const INITIALIZE_PENDING = "INITIALIZE_PENDING";
export const INITIALIZE_FULFILLED = "INITIALIZE_FULFILLED";
export const INITIALIZE_REJECTED = "INITIALIZE_REJECTED";

export const BUY_DATA = "BUY_DATA";
export const BUY_DATA_PENDING = "BUY_DATA_PENDING";
export const BUY_DATA_FULFILLED = "BUY_DATA_FULFILLED";
export const BUY_DATA_REJECTED = "BUY_DATA_REJECTED";

export const UPDATE_WALLET = "UPDATE_WALLET";
export const UPDATE_WALLET_PENDING = "UPDATE_WALLET_PENDING";
export const UPDATE_WALLET_FULFILLED = "UPDATE_WALLET_FULFILLED";
export const UPDATE_WALLET_REJECTED = "UPDATE_WALLET_REJECTED";

export const BUY_AIRTIME = "BUY_AIRTIME";
export const BUY_AIRTIME_PENDING = "BUY_AIRTIME_PENDING";
export const BUY_AIRTIME_FULFILLED = "BUY_AIRTIME_FULFILLED";
export const BUY_AIRTIME_REJECTED = "BUY_AIRTIME_REJECTED";
